{% set name = "splipy" %}
{% set version = "1.5.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Splipy-{{ version }}.tar.gz
    sha256: 09d4a3b173ec883c7309625ebdff4ece9721fc80c0efd2bd70f069ecb73ac76a
  - path: COPYING
    sha256: 3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy >=1.20
    - pip
    - python
  run:
    - python
    - scipy >=1.2

test:
  imports:
    - splipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sintefmath/Splipy
  summary: Spline modelling library for Python
  doc_url: https://pythonhosted.org/Splipy/
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - conda-forger
